#ifndef DEFAULT_VAR_HPP_
#define DEFAULT_VAR_HPP_

namespace reprize
{
namespace res
{
namespace def
{
Char sys_material[] = // material is based on 'Texture' and 'Shader'.
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
" <Material name=\"Arrow\">"
"  <Texture name=\"\" uv=\"\" size=\"\" ref=\"/System/Texture/Arrow\"/>"
" </Material>"
" <Material name=\"Button\">"
"  <Texture ref=\"/System/Texture/Button\"/></Material>"
" <Material name=\"Beam\">"
"  <Texture ref=\"/System/Texture/Beam\"/></Material>"
" <Material name=\"Black\">"
"  <Texture ref=\"/System/Texture/Black\"/></Material>"
" <Material name=\"Border\">"
"  <Texture ref=\"/System/Texture/Border\"/></Material>"
" <Material name=\"Default\">"
"  <Texture ref=\"/System/Texture/Default\"/></Material>"
" <Material name=\"White\">"
"  <Texture ref=\"/System/Texture/White\"/></Material>"
" <Material name=\"Frame\">"
"  <Texture ref=\"/System/Texture/Frame\"/></Material>"
" <Material name=\"Thumb\">"
"  <Texture ref=\"/System/Texture/Thumb\"/></Material>"
" <Material name=\"Transparent\">"
"  <Texture ref=\"/System/Texture/Transparent\"/></Material>"
" <Material name=\"Fallback\">"
"  <Texture ref=\"/System/Texture/Fallback\"/></Material>"
"</Reprize>";

Char sys_theme[] = // theme is based on 'Background', 'Font'.
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
" <Theme name=\"Default\" def=\"/Define/Theme\">"
"  <Button pad=\"4 4\""
"          bg=\"/System/Material/Button\" font=\"/System/Font/ReFont\"/>"
"  <Canvas pad=\"4 4\""
"          bg=\"/System/Material/Button\" font=\"/System/Font/ReFont\"/>"
"  <CheckBox pad=\"0 0\""
"            bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
"  <Cursor pad=\"4 4\""
"          bg=\"/System/Material/Arrow\" font=\"/System/Font/ReFont\"/>"
"  <Div bg=\"/System/Material/Transparent\"/>"
"  <TextBox pad=\"4 4\""
"           bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
"  <KeyBox pad=\"4 4\""
"          bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
"  <LogBox pad=\"4 4\""
"          bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
"  <Frame pad=\"4 4\""
"         bg=\"/System/Material/Frame\" font=\"/System/Font/ReFont\"/>"
"  <ScrollBar pad=\"6 6\"bg=\"/System/Material/Frame\"/>"
"  <Slider pad=\"4 4\""
"          bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
"  <TabBox pad=\"4 4\""
"          bg=\"/System/Material/Thumb\" font=\"/System/Font/ReFont\"/>"
"  <Thumb pad=\"4 4\""
"         bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
"  <Pulldown pad=\"4 4\""
"            bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
"  <Caption pad=\"0 0\""
"           bg=\"/System/Material/Transparent\" font=\"/System/Font/ReFont\"/>"
"  <Window pad=\"4 4\""
"          bg=\"/System/Material/Border\" font=\"/System/Font/ReFont\"/>"
" </Theme>"
"</Reprize>";

// gui is based on 'Desktop' and children of 'Widget'.
Char sys_desktop[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
" <Desktop name=\"SysDesktop\" size=\"800 600\""
"          def=\"/System/Theme/Default\">"
"  <Cursor name=\"SysCursor\"/>"

/*
"  <Window name=\"SysMenu\" draggable=\"500 500 0\">"
"    Reprize Menu"
"    <Frame align=\"center\">"
"     <Button size=\"120\" align=\"center\">"
"      Start Roaming</Button>"
"     <Button size=\"120\" align=\"center\">"
"      Edit Session</Button>"
"     <Button size=\"120\" align=\"center\">"
"      Configuration</Button>"
"     <Button size=\"120\" align=\"center\">"
"      Show Console</Button>"
"     <Button size=\"120\" align=\"center\">"
"      Credit</Button>"
"     <Button size=\"120\" align=\"center\""
"             target=\"/Interface/Avatar/quit\">"
"      Exit</Button>"
"    </Frame>"
"  </Window>"

"  <Window name=\"SysSession\" pos=\"300 300 0\" draggable=\"on\">"
"   Edit Session"
"   <Frame align=\"center\">"
"    <Div>Space settings</Div>"
"    <Div>Magnitude<Slider size=\"120\">a</Slider></Div>"
"    <CheckBox align=\"middle\">Mumu</CheckBox>"
"    <Button size=\"140\" align=\"center\">Regeneration</Button>"
"--------"
"V<TextBox size=\"120\">Mumu</TextBox>"
"S<TextBox size=\"120\">Mumu</TextBox>"
"Gamma<TextBox size=\"120\">Mumu</TextBox>"
"P<TextBox size=\"120\">Mumu</TextBox>"
"    <Button size=\"140\" align=\"center\">Generate</Button>"
"   </Frame>"
"  </Window>"

"  <Window name=\"SysConf\" draggable=\"on\">"
"    Configulation"
"    <Frame align=\"center\">"
"     <Div>Pointer Settings</Div>"
"     <Div>Sensitivity<Slider size=\"120\">a</Slider></Div>"
"     <Div>X-Y Ratio<Slider size=\"120\" align=\"center\">a</Slider></Div>"
"     <CheckBox align=\"middle\">Invert Y</CheckBox>"
"     <Div align=\"left\" size=\"200 0\">Keyboard Settings</Div>"
// "     <Div align=\"middle\">"
// "      <Div align=\"right\" size=\"80 0\">Forward :</Div>"
// "      <KeyBox size=\"120 8\" cmd=\"/Interface/Avatar/Control/Bind +forward\""
// "              content=\"/Interface/Avatar/Control/Bind\"/>"
// "     </Div>"
// "     <Div align=\"middle\">"
// "      <Div align=\"right\" size=\"80 0\">Back :</Div>"
// "      <KeyBox size=\"120 8\" cmd=\"/Interface/Avatar/Control/Bind +back\""
// "              content=\"/Interface/Avatar/Control/Bind\"/>"
// "     </Div>"
// "     <Div align=\"middle\">"
// "      <Div align=\"right\" size=\"80 0\">Right :</Div>"
// "      <KeyBox size=\"120 8\" cmd=\"/Interface/Avatar/Control/Bind +right\""
// "              content=\"/Interface/Avatar/Control/Bind\"/>"
// "     </Div>"
// "     <Div align=\"middle\">"
// "      <Div align=\"right\" size=\"80 0\">Left :</Div>"
// "      <KeyBox size=\"120 8\" cmd=\"/Interface/Avatar/Control/Bind +left\""
// "              content=\"/Interface/Avatar/Control/Bind\"/>"
// "     </Div>"
// "     <Div align=\"middle\">"
// "      <Div align=\"right\" size=\"80 0\">Up :</Div>"
// "      <KeyBox size=\"120 8\" cmd=\"/Interface/Avatar/Control/Bind +up\""
// "              content=\"/Interface/Avatar/Control/Bind\"/>"
// "     </Div>"
// "     <Div align=\"middle\">"
// "      <Div align=\"right\" size=\"80 0\">Down :</Div>"
// "      <KeyBox size=\"120 8\" cmd=\"/Interface/Avatar/Control/Bind +down\""
// "              content=\"/Interface/Avatar/Control/Bind\"/>"
// "     </Div>"
"    </Frame>"
"  </Window>"
*/

"  <Window name=\"SysConsole\" draggable=\"on\">"
"   Console"
"    <Frame title=\"Moin\" shade=\"off\">"
"     <LogBox size=\"360 240\" src=\"/Log/Global\"/>"
"     <TextBox size=\"360 0\" property=\"/.eval\">...</TextBox>"
"    </Frame>"
"  </Window>"
/*
"  <Window name=\"SysCredit\" draggable=\"on\">"
"   Credit"
"   <Frame size=\"120\" align=\"center\">"
"    <Div>Reprize engine</Div>"
"    <Div align=\"center\">Development Release 1</Div>"
"    <Div size=\"120\" align=\"middle\">- -</Div>"
"     <Div align=\"left\">Produced by Tatsuhiko Suzuki</Div>"
"     <Div align=\"left\">http://reprize.org/</Div>"
"   </Frame>"
"  </Window>"
*/
" </Desktop>"
"</Reprize>";

Char sys_generator[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
"  <Generator def=\"/Define/Generator\">"
"    <GeomGen name=\"l-system\" script=\"/System/Script/LSystem\" type=\"ico\""
"             begin=\"10 10 10\" end=\"-1 -1 -1\" dim=\"1 1 1\" face=\"back\">"
"             mogera"
"    </GeomGen>"
"    <GeomGen name=\"ico\" script=\"/System/Script/Primitive\" type=\"ico\""
"             begin=\"10 10 10\" end=\"-1 -1 -1\" dim=\"1 1 1\" face=\"back\">"
"             mogera"
"    </GeomGen>"
"    <GeomGen name=\"box\" script=\"/System/Script/Primitive\" type=\"box\""
"             begin=\"10 10 10\" end=\"-1 -1 -1\" dim=\"1 1 1\" face=\"back\">"
"             bogera"
"    </GeomGen>"
"    <GeomGen name=\"plane\" script=\"/System/Script/Primitive\" type=\"isometric\""
"             begin=\"10 10 10\" end=\"100 100 100\" dim=\"10 10 10\" face=\"back\">"
"             pogera"
"    </GeomGen>"
"    <TopoloGen name=\"topology\" script=\"/System/Script/LSystem\" type=\"ico\""
"               begin=\"10 10 10\" end=\"-1 -1 -1\" dim=\"1 1 1\" face=\"back\""
"               geometry=\"/System/Generator/Generator/box\">"
"               mogera"
"    </TopoloGen>"
"  </Generator>"
"</Reprize>";

Char sys_model[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
" <Model name=\"Skydome_mdl\" geometry=\"/System/Generator/Generator/ico\""
"        material=\"/System/Material/Default\"/>"
" <Model name=\"Blofig_mdl\" geometry=\"/System/Generator/Generator/box\""
"        material=\"/System/Material/Default\"/>"
" <Model name=\"Plane_mdl\" geometry=\"/System/Generator/Generator/plane\""
"        material=\"/System/Material/Default\"/>"
"</Reprize>";

Char sys_actor[] = // actor is based on 'Model' and 'Script'.
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
"  <Actor name=\"fig\"/>"
// "  <Actor name=\"Boid\">"
// "    <Model>/System/Model/testmdl</Model>"
// "    <Script name=\"jikkendai\">/System/Script/Primitive</Script>"
// "  </Actor>"
// "  <Actor name=\"Plants\" script=\"/Blueprint/Globe\""
// "         type=\"box\" width=\"16\" height=\"16\""
// "         face=\"front\" dim=\"10\" size=\"10\" xdim=\"8\" ydim=\"8\""
// "         begin=\"1 2 3\" end=\"100 200 300\"/>"
"  <Actor name=\"Blofig\"  model=\"/System/Model/Blofig_mdl\"/>"
"  <Actor name=\"Plane\"   model=\"/System/Model/Plane_mdl\"/>"
"  <Actor name=\"Skydome\" model=\"/System/Model/Skydome_mdl\"/>"
"</Reprize>";

Char sys_space[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
"  <Space name=\"testspace0\">"
"   <Actor pos=\"0 0 0\" new=\"/System/Actor/Blofig\"/>"
"   <Actor pos=\"0 0 -100\" new=\"/System/Actor/Plane\"/>"
"  </Space>"
"  <Space name=\"Ground\" model=\"/System/Model/Plane_mdl\">"
"   <Actor pos=\"0 0 0\" new=\"/System/Actor/Blofig\"/>"
"  </Space>"
// "   <Metric name=\"Metric0\"/>"
// "   <Topology name=\"Topology0\"/>"
"  <Space name=\"Skydome\" model=\"/System/Model/Skydome_mdl\">"
// "    <Actor name=\"skactor1\" pos=\"0 0 0\" new=\"/System/Actor/Skydome\"/>"
"    <Actor pos=\"100 100 100\" new=\"/System/Actor/Blofig\"/>"
"  </Space>"
"</Reprize>";

Char sys_scene[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
"  <Scene name=\"SysBackdrop\" pos=\"0 0 0\">"
"    <Space pos_ratio=\"0 0 0\" dir_ratio=\"0 0 0\" ref=\"/System/Space/Skydome\"/>"
"  </Scene>"
"  <Scene name=\"SysWorld\" pov=\"/System/Actor/fig\">"
"   <Space pos=\"0 0 0\" pov=\"/System/Actor/fig\" ref=\"/System/Space/Ground\"/>"
// "   <Actor pos=\"0 0 0\" ref=\"/System/Actor/Plane\"/>"
"   <Actor pos=\"0 0 0\" ref=\"/System/Actor/fig\"/>"
"  </Scene>"
"  <Scene name=\"SysOverlay\" fov=\"ortho\">"
"  </Scene>"
"</Reprize>";

Char sys_stage[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
"  <Stage name=\"SysStage\""
"         overlay=\"/System/Scene/SysOverlay\""
"         world=\"/System/Scene/SysWorld\""
"         backdrop=\"/System/Scene/SysBackdrop\""
"         menu=\"/System/Desktop/SysDesktop\""
"         hud=\"/System/HUD/SysHUD\"/>"
"</Reprize>";

Char sys_hud[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
" <HUD name=\"SysHUD\" def=\"/System/Theme/Default\">"
"  <Button pos=\"120 120 0\" size=\"120\" align=\"center\">Start Roaming</Button>"
// "  <Div>konnnannmo detari (302, 330, 100)</Div>"
"  <Div src=\"/System/Actor/fig\">mogemogemoge</Div>"
// "    <String pos=\"\" size=\"\"/>"
// "    <LogBox pos=\"\" size=\"\"/>"
// "    <LineChart pos=\"\" size=\"\" src=\"whereever.property\"/>"
// "    <PieChart pos=\"\" size=\"\" src=\"whereever.property\"/>"
// "    <BarChart pos=\"\" size=\"\" src=\"whereever.property\"/>"
"  </HUD>"
"</Reprize>";

Char sys_startup[] =
"<Reprize>"
" <Startup>"
"  <Permission type=\"root\"/>"
"  <Config>/Resource/config.xml</Config>"
"  <Session>/System/Stage/SysStage</Session>"
" </Startup>"
"</Reprize>";

Char config_default[] =
"<?xml version=\"1.0\" ?>"
"<Reprize version=\"0.0\">"
" <Config>"
"  <Resource>"
"   <Hunk size=\"128\"/>"
"  </Resource>"
"  <Audio>"
"   <Effect volume=\"1\" invert=\"off\" echo=\"4\" source=\"16\""
"           frequency=\"44\"/>"
"   <Music volume=\"1\" frequency=\"44\"/>"
"  </Audio>"
"  <Input>"
"   <Keyboard os_systemkey=\"off\"/>"
"   <Mouse os_systemkey=\"off\"/>"
"   <Touch os_systemkey=\"off\"/>"
"  </Input>"
"  <Interface>"
"   <Desktop handle=\"slippery\" doubleclick=\"500\">"
"    <Theme color=\"1 1 1 1\" appearance=\"vanilla\"/>"
"   </Desktop>"
"   <Avatar test=\"hogera\">"
"    <Control bind=\"K_ESCAPE\"/>"
"    <Control bind=\"K_1 action/select/barehand\"/>"
"    <Control bind=\"K_2 action/select/edged\"/>"
"    <Control bind=\"K_3 action/select/bltype\"/>"
"    <Control bind=\"K_4 action/select/polearm\"/>"
"    <Control bind=\"K_5 action/select/missile\"/>"
"    <Control bind=\"K_6 action/select/potion\"/>"
"    <Control bind=\"K_7 action/select/tool\"/>"
"    <Control bind=\"K_8 action/select/armor\"/>"
"    <Control bind=\"K_9 action/select/wand\"/>"
"    <Control bind=\"K_0 action/select/book\"/>"
"    <Control bind=\"K_W forward\"/>"
"    <Control bind=\"K_A left\"/>"
"    <Control bind=\"K_S back\"/>"
"    <Control bind=\"K_D right\"/>"
"    <Control bind=\"K_SPACE up\"/>"
"    <Control bind=\"K_LMENU down\"/>"
"    <Control bind=\"K_LSHIFT action/speed\"/>"
"    <Control bind=\"K_T chat/global\"/>"
"    <Control bind=\"K_Y chat/team\"/>"
"    <Control bind=\"K_TAB info\"/>"
"    <Control bind=\"K_LCONTROL action/gesture\"/>"
"    <Control bind=\"K_CAPITAL action/yell\"/>"
"    <Control bind=\"M_BUTTON0 action/hand/right\"/>"
"    <Control bind=\"M_BUTTON1 action/hand/left\"/>"
"    <Control bind=\"M_BUTTON2 action/select/next\"/>"
"    <Control bind=\"M_BUTTON3 action/select/previous\"/>"
"    <Control bind=\"M_BUTTON4 action/apply\"/>"
"    <Pointer sensitivity=\"5\" pitch=\"0.22\" yaw=\"0.22\" invert=\"on\"/>"
"    <Pointer bind=\"5\"/>"
"   </Avatar>"
"  </Interface>"
"    <HUD name=\"hogebu\" def=\"/System/Theme/Default\">"
"     <Crosshair color=\"1 1 1 1\" size=\"1\""
"                material=\"/System/Material/Frame\"/>"
"     <Button size=\"140\" align=\"center\">Actor</Button>"
"     <Button size=\"140\" align=\"center\">Sky</Button>"
"    </HUD>"
"  <Network>"
"   <Client>"
"   </Client>"
"   <Server rate=\"5000\" snaps=\"20\" fps=\"20\">"
"    <Account>"
"     <Banned name=\"John Doe\" mac=\"FFFFFFFFFFFF\"/>"
"    </Account>"
"   </Server>"
"  </Network>"
"  <Physics>"
"   <RigidBody collision=\"on\" impulse=\"on\"/>"
"   <ElasticBody collision=\"on\" impulse=\"on\"/>"
"  </Physics>"
"  <Video>"
"   <Display fullscreen=\"on\" width=\"800\" height=\"600\" depth=\"32\""
"            maxfps=\"100\"/>"
"   <Effect>"
"    <Particle particle=\"64\" lifetime=\"1\" reflection=\"on\"/>"
"    <Skinning ik=\"on\"/>"
"    <Shader quality=\"1\" jit=\"on\"/>"
"   </Effect>"
"  </Video>"
"  <Avatar name=\"unnamed\">"
"   <Figure face=\"0\" >"
"    <Gene type=\"0\" gender=\"XX\" melanin=\"0.5\"/>"
"    <Face type=\"0\"/>"
"    <Proportion scale=\"0.8\" ratio=\"0.5\"/>"
"   </Figure>"
"  </Avatar>"
"  <World>"
"   <Gravity scale=\"0.98\" dir=\"1 1 1\"/>"
"   <Map ref=\"/Resource/Map/sandbox\"/>"
"  </World>"
"  <Rule>"
"  </Rule>"
" </Config>"
"</Reprize>";
}
}
}
#endif
